config/routes.rb
SociaLoginRails::Application.routes.draw do

  resources :genres

  root :to => 'pages#landing'
  namespace :admin do
    resources :users
    resources :admin_users
  end

  resources :roles

  resources :songs do
    match "get_30_seconds_song" , :via=>[:get]
  end
   
  #match "/admin_users" => "users#admin_users", :via=>[:get]
  match "/add_email" => "users#add_email" , :via=>"get"
  match "/users/save_email"=> "users#save_email", :via=>"post"
  get "pages/terms"
  get "pages/welcome"
  get "pages/landing"
  match "/twitter" => 'pages#landing' ,:via=>"get"
  devise_for :users, :controllers => {:passwords => "passwords",:omniauth_callbacks=> "omniauth_callbacks",:sessions => "api/v1/sessions",:registrations=>"api/v1/registrations"}
 resources :users
  


  namespace :api do
    namespace :v1 do
      #Sessions controller
      devise_scope :user do
        resources :sessions, :only => [:create, :destroy,:update,:api_current_user]
        match 'api_current_user/:id' => "sessions#api_current_user" ,:via => :get
        #        match 'all_users' => "sessions#all_users" ,:via => :get
        match 'date_today' => "sessions#date_today", :via => :get   
        match 'reset_password' => "sessions#reset_password", :via => :post
        match 'users' => "registrations#create" ,:via=>[:post]
        match 'edit' => "registrations#update" ,:via=>[:post]
      end
    end
  end
end

app/models/admin/admin_user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default("")
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  authentication_token   :string(255)
#  age_range              :string(255)
#  status                 :string(255)      default("Inactive")
#

class Admin::AdminUser < ActiveRecord::Base
  self.table_name = "users"
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/admin_users_controller.rb
class Admin::AdminUsersController < InheritedResources::Base
before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @admin_users = User.get_admin_user
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @admin_user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @admin_user = User.new(user_params)

    respond_to do |format|
      if @admin_user.save
        @admin_user.set_admin_role
        format.html { redirect_to admin_user_url(@admin_user), notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(user_params)
        format.html { redirect_to admin_user_url(@admin_user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_user_url }
      format.json { head :no_content }
    end
  end

  def admin_user_url(user)
  	admin_admin_users_path(user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @admin_user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :age_range)
    end
end

app/views/admin/admin_users/_form.html.erb
<%= form_for(@admin_user, :url => admin_admin_users_path(@admin_user)) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true, :autofocus => true %><br/>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :required => true, :autofocus => true  %><br/>
  </div>
  <div class="field">
     <%= f.label :password, :required => true  %><br/>
     <%= f.password_field :password, :required => true  %><br/>
  </div>
  <div class="field">
    <%= f.label :age_range, :required => true  %><br/>
    <%= f.select :age_range, User::AGE_OPTIONS, :selected => User::SELECTED_AGE_OPTION %><br/>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/admin_users/edit.html.erb
<h1>Editing admin_user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_admin_users_path %>

app/views/admin/admin_users/index.html.erb
<h1>Listing admin_users</h1>

<table>
  <thead>
    <tr>
      <th> Name </th>
      <th> Age Range </th>
      <th> Email </th>
      <th> Status </th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.name %></td>
        <td><%= admin_user.age_range %></td>
        <td><%= admin_user.email %></td>
        <td><%= admin_user.status %></td>
        <td><%= link_to 'Show', admin_user %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
        <% unless admin_user.inactive_user? %>
          <td><%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_admin_user_path %>

app/views/admin/admin_users/new.html.erb
<h1>New admin_user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_admin_users_path %>

app/views/admin/admin_users/show.html.erb
<%= link_to 'Edit', edit_admin_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_admin_users_path %>