config/routes.rb
SociaLoginRails::Application.routes.draw do

  resources :genres

  root :to => 'pages#landing'
  namespace :admin do
    resources :users
    resources :admin_users
  end

  resources :roles

  resources :songs do
    match "get_30_seconds_song" , :via=>[:get]
  end
   
  #match "/admin_users" => "users#admin_users", :via=>[:get]
  match "/add_email" => "users#add_email" , :via=>"get"
  match "/users/save_email"=> "users#save_email", :via=>"post"
  get "pages/terms"
  get "pages/welcome"
  get "pages/landing"
  match "/twitter" => 'pages#landing' ,:via=>"get"
  devise_for :users, :controllers => {:passwords => "passwords",:omniauth_callbacks=> "omniauth_callbacks",:sessions => "api/v1/sessions",:registrations=>"api/v1/registrations"}
 resources :users
  


  namespace :api do
    namespace :v1 do
      #Sessions controller
      devise_scope :user do
        resources :sessions, :only => [:create, :destroy,:update,:api_current_user]
        match 'api_current_user/:id' => "sessions#api_current_user" ,:via => :get
        #        match 'all_users' => "sessions#all_users" ,:via => :get
        match 'date_today' => "sessions#date_today", :via => :get   
        match 'reset_password' => "sessions#reset_password", :via => :post
        match 'users' => "registrations#create" ,:via=>[:post]
        match 'edit' => "registrations#update" ,:via=>[:post]
      end
    end
  end
end

app/models/admin/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default("")
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  authentication_token   :string(255)
#  age_range              :string(255)
#  status                 :string(255)      default("Inactive")
#

class Admin::User < ActiveRecord::Base
	self.table_name = "users"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default("")
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  authentication_token   :string(255)
#  age_range              :string(255)
#  status                 :string(255)      default("Inactive")
#

class User < ActiveRecord::Base
 

  devise :database_authenticatable, :registerable,:confirmable,:validatable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_presence_of :email
  validate :password_complexity
  validate :name_valid_format , :if => :new_record?
  validates_presence_of :name

  has_many :authorizations, :dependent=>:destroy
  has_one :role, :dependent=>:destroy


  after_save :create_role
  
  acts_as_token_authenticatable

  AGE_OPTIONS = {
    "Below 18"=>"Below 18",
    "19-24"=>"19-24",
    "25+"=>"25+"
  }

  SELECTED_AGE_OPTION= {
    "Below 18"=>"Below 18"
  }


  EXISTING_ACCOUNT = 'This account is already registered with another user.'


  before_save :ensure_authentication_token!
  before_save :set_age_range_if_25



 
  #--
  # Created By: Chaitali Khangar
  # Purpose: To set age range if 25 came from api
  # Created On: 07/05/2014
  #++
  def set_age_range_if_25
    self.age_range = self.age_range == 25.to_s ? "25+" : self.age_range
  end

  #--
  # Created By: Chaitali Khangar
  # Purpose: To generate secure token string
  # Created On: 05/05/2014
  #++
  def generate_secure_token_string
    SecureRandom.urlsafe_base64(25).tr('lIO0', 'sxyz')
  end

  #--
  # Created By: Chaitali Khangar
  # Purpose: To ensure authentication token
  # Created On: 05/05/2014
  #++
  def ensure_authentication_token!
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end


  #--
  # Created By: Chaitali Khangar
  # Purpose: To generate authentication token
  # Created On: 05/05/2014
  #++

  def generate_authentication_token
    loop do
      token = generate_secure_token_string
      break token unless User.where(:authentication_token=>token).first
    end
  end

  #--
  # Created By: Chaitali Khangar
  # Purpose: To reset authentication token
  # Created On: 05/05/2014
  #++

  def reset_authentication_token!
    self.authentication_token = generate_authentication_token
    self.save!
  end

  #--
  # Created By: Chaitali Khangar
  # Purpose: To check validation for name
  # Created On: 18/04/2014
  #++

  def name_valid_format
    if name.present? and not name.match(/[\w]+([\s]+[\w]+){1}+/)
      errors.add :name , "must be seperated by space and should not contain any special characters."
    end
  end


  #--
  # Created By: Chaitali Khangar
  # Purpose: To check password complexity
  # Created On: 18/04/2014
  #++
  def password_complexity
    if password.present? and not password.match(/(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
    end
  end


  #--
  # Created By: Chaitali Khangar
  # Purpose: To create new session
  # Created On: 22/04/2014
  #++

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end


  def create_role
    role = Role.where(:user_id=>self.id)
    role = role.first || (self.build_role && self.save)
  end

  #--
  # Created By: Chaitali Khangar
  # Purpose: To create authorization by provider
  # Created On: 22/04/2014
  #++

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s)
    if authorization.first.present? && current_user
      current_user.errors.add_to_base(EXISTING_ACCOUNT) and return(current_user)
    end
    unless authorization.first.present?
      authorization = Authorization.new(:provider => auth.provider, :uid => auth.uid.to_s,:token=>auth.credentials.token)
      if authorization.user.blank?
        user = current_user.nil? ? User.where('email = ?', auth["info"]["email"]).first : current_user
        if user.blank?
          user = User.new
          user.password = Devise.friendly_token[0,10]
          user.name = auth.info.name
          user.email = auth.info.email
          user.skip_confirmation!
          auth.provider == "twitter" ?  user.save(:validate => false) :  user.skip_confirmation! && user.save
        end
        user.age_range =  (auth.provider== "facebook" && auth.extra.raw_info && auth.extra.raw_info.birthday.present?  ?  User.calculate_age_range(Date.strptime(auth.extra.raw_info.birthday,'%m/%d/%Y')) : nil)
        user.skip_confirmation!
        user.save!
        authorization.user_id = user.id
        authorization.secret = auth.credentials.secret
        authorization.save
      end
    else
      authorization = authorization.first
      authorization.token = auth.credentials.token
      authorization.secret = auth.credentials.secret
      authorization.save
    end
    authorization
  end


  #--
  # Created By: Chaitali Khangar
  # Purpose: To calculate age range
  # Created On: 22/04/2014
  #++
  def self.calculate_age_range(user_age)
    current_year = Date.today.strftime("%Y")
    user_year = user_age.strftime("%Y")
    age = current_year.to_i - user_year.to_i
    return "Below 18" if age.between?(0,18)
    return "19-24" if age.between?(19,24)
    return "25+" if age > 24
  end
  
  #--
  # Created By: Chaitali Khangar
  # Purpose: To save email
  # Created On: 29/04/2014
  #++
  def self.save_email_address(params)
    user = User.find(params[:user][:id])
    user.email = params[:user][:email]
    user
  end


  #--
  # Created By: Chaitali Khangar
  # Purpose: To generate password randomely
  # Created On: 5/5/2014
  #++

  def generate_password
    password = [('a'..'z'), ('A'..'Z'),(0..9)].map { |i| i.to_a }.flatten
    (8...32).map { password[rand(password.length)] }.join
  end

  #--
  # Created By: Chaitali Khangar
  # Purpose: To check token
  # Created On: 5/5/2014
  #++
  def self.confirm_by_token(confirmation_token)
    original_token     = confirmation_token
    confirmation_token = confirmation_token #Devise.token_generator.digest(self, :confirmation_token, confirmation_token)
    
    confirmable = find_or_initialize_with_error_by(:confirmation_token, confirmation_token)
    confirmable.confirm! if confirmable.persisted?
    confirmable.confirmation_token = original_token
    confirmable

  end

    #--
  # Created By: Chaitali Khangar
  # Purpose: To check user is admin or not
  # Created On: 5/5/2014
  #++
  def is_admin?
   self.role.role_name == "Admin"
  end

    #--
  # Created By: Chaitali Khangar
  # Purpose: To get normal users
  # Created On: 5/5/2014
  #++
  def self.get_normal_user
    includes(:role).where("roles.role_name=?", "User")
  end


      #--
  # Created By: Chaitali Khangar
  # Purpose: To get admin users
  # Created On: 5/5/2014
  #++
  def self.get_admin_user
    includes(:role).where("roles.role_name=?", "Admin")
  end

      #--
  # Created By: Chaitali Khangar
  # Purpose: To check inactivge user
  # Created On: 5/5/2014
  #++
  def inactive_user?
    self.status == "Inactive"
  end

  def set_admin_role
    self.build_role(:role_name => "Admin")
    self.save
  end

  def set_normal_user_role
    self.build_role(:role_name => "User")
    self.save
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < InheritedResources::Base
before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @admin_users = User.get_normal_user
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @admin_user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @admin_user = User.new(user_params)

    respond_to do |format|
      if @admin_user.save
        @admin_user.set_normal_user_role
        format.html { redirect_to admin_user_url(@admin_user), notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(user_params)
        format.html { redirect_to admin_user_url(@admin_user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_user_url }
      format.json { head :no_content }
    end
  end

  def admin_user_url(user)
  	admin_user_path(user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @admin_user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :age_range)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, :only=> [:show, :edit, :update,:add_email]
  before_filter :validate_authorization_for_user, :only=> [:edit, :update]
  before_action :check_admin, except: [:add_email,:save_email]


  def admin_users
    @users = User.get_admin_user
  end

  def index
    @users = User.get_normal_user
  end

  def show
    redirect_to "/add_email?id=#{current_user.id}" and return unless @user.email?
  end


  def destroy
    @user = User.find(params[:id])
    if @user.update_attributes(:status=>"Inactive")
      flash[:notice] = "User status in inactive."
    end
    redirect_to :back
  end

  def edit
  end

  def add_email
  end

  #--
  # Created By: Chaitali khangar
  # Purpose: To save email
  # Created On: 23/04/2014
  #++
  def save_email
    @user = User.save_email_address(params)
    if @user.save(:validations => {:except => :name})
      redirect_to root_url, :notice=> 'User email was successfully updated.'
    else
      flash[:error] = @user.errors.full_messages.uniq.join("\n")
      render :action=> 'add_email',:id=>@user.id
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def validate_authorization_for_user
    redirect_to root_path unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :age_range)
  end

  def check_admin
    if signed_in?
      flash[:alert]=  'Only admins allowed!' unless current_user.is_admin?
      redirect_to root_url
    else
      # or you can use the authenticate_user! devise provides to only allow signed_in users
      flash[:alert]= 'Please sign in!'
      redirect_to root_url
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@admin_user, :url => "/admin"+url_for(@admin_user)) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true, :autofocus => true %><br/>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :required => true, :autofocus => true  %><br/>
  </div>
  <div class="field">
     <%= f.label :password, :required => true  %><br/>
     <%= f.password_field :password, :required => true  %><br/>
  </div>
  <div class="field">
    <%= f.label :age_range, :required => true  %><br/>
    <%= f.select :age_range, User::AGE_OPTIONS, :selected => User::SELECTED_AGE_OPTION %><br/>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing admin_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<!--<%#*<h1>Listing admin_users</h1>%>

<%#*<table>%>
<%#*<thead>%>
<%#*<tr>%>
<%#*<th> Name </th>%>
<%#*<th> Age Range </th>%>
<%#*<th> Email </th>%>
<%#*<th> Status </th>%>
<%#*<th></th>%>
<%#*<th></th>%>
<%#*<th></th>%>
<%#*</tr>%>
<%#*</thead>%>

<%#*<tbody>%>
<%# @admin_users.each do |admin_user| %>
<%#*<tr>%>
<%#*<td><%= admin_user.name %></td>%>
<%#*<td><%= admin_user.age_range %></td>%>
<%#*<td><%= admin_user.email %></td>%>
<%#*<td><%= admin_user.status %></td>%>
<%#*<td><%= link_to 'Show', admin_user %></td>%>
<%#*<td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>%>
<%# unless admin_user.inactive_user? %>
<%#*<td><%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>%>
<%# end %>
<%#*</tr>%>
<%# end %>
<%#*</tbody>%>
<%#*</table>%>

<%#*<br>%>

<%#= link_to 'New User', new_admin_user_path %>
-->


<!-- AUI Framework -->
<!DOCTYPE html>
    <html>
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Blue Music</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <!-- Favicons -->

        <!--[if lt IE 9]>
          <script src="assets/js/minified/core/html5shiv.min.js"></script>
          <script src="assets/js/minified/core/respond.min.js"></script>
        <![endif]-->

        <!--[if lt IE 7]>
        <link rel="stylesheet" type="text/css" href="assets/css/minified/icons-ie7.min.css">
        <![endif]-->

        <!-- BlueMusic CSS Core -->
        <%= stylesheet_link_tag "bootstrap.min.css","blue.min.css" %>
        <%#*<link href="assets/css/minified/bootstrap.min.css" rel="stylesheet" type="text/css" />%>

        <%#*<link rel="stylesheet" type="text/css" href="assets/css/minified/blue.min.css">%>

        <!-- <link rel="stylesheet" type="text/css" href="../_assets/css/widgets/theme-switcher.css"> -->
        <!-- Theme UI -->

        <link id="layout-theme" rel="stylesheet" type="text/css" href="../_assets/themes/agileui/color-schemes/layouts/default.html">
        <link id="elements-theme" rel="stylesheet" type="text/css" href="../_assets/themes/agileui/color-schemes/elements/default.html">

        <link rel="stylesheet" type="text/css" href="../_assets/themes/agileui/responsive.html">
        <link rel="stylesheet" type="text/css" href="../_assets/css/helpers/responsive-elements.html">

        <!-- BlueMusic JS -->

        <script type="text/javascript" src="../assets/js/minified/aui-production.min.js"></script>

 
        <link href="../assets/javascript/jquery.metisMenu.css" rel="stylesheet" type="text/css" />
    </head>
    <body style="background-color:#f3f5f7;">
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <div id="login-page">


        <div class="pad20A">
            <div class="row">
                <form  class="col-md-4 center-margin form-vertical" method="">
                    <div class="ui-dialog modal-dialog login-bg" id="login-form">
                       <div class="row">
                        <div class="col-md-4 center-margin" style="background-color:#fff; padding:0px; border:1px solid #ececec; height:500px; margin-bottom:0px; width:97%;">
                            <div class="col-md-3" style="background-color:#2b2f3e; height:100%;" >
                                 <ul id="menu">
                                    <li class="active" style="border:0px;">
                                      <a href="<%= edit_user_registration_path   %>"><i class="glyph-icon icon-edit"></i> &nbsp; Profile </a>
  
                                    </li>
                                    <li  style="border:0px;">
                                      <a href="<%=  admin_users_path %>"><i class="glyph-icon icon-music"></i> &nbsp; Manage user </a>
 
                                    </li>
                                    <li  style="border:0px;">
                                      <a href="<%= admin_admin_users_path %>"><i class="glyph-icon icon-headphones"></i> Manage Admin user </a>
                                    </li>
                                        <li  style="border:0px;">
                                          <a href="<%= songs_path %>"><i class="glyph-icon icon-headphones"></i> Manage Music </a>
                                    </li>
                                           </li>
                                        <li  style="border:0px;">
                                          <a href="<%=  destroy_user_session_path %>"><i class="glyph-icon icon-headphones"></i> Logout </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-8" style="height:100%; padding:10px;" >
                               <div class="cart-heading">Music List</div>
                               <div class="cart-title-one">
                                <div class="w20 float-left">Image</div>
                                <div class="w40 float-left">Album Name</div>
                                <div class="w20 float-left">Artist</div>
                                <div class="w10 float-left">Play</div>
                                <div class="w10 float-left">Remove</div>
                               </div>
                               <div class="clearfix"></div>
                               <div class="cart-div">
                                <div class="w20 float-left"><img src="assets/images/cart-img.jpg" width="20px" /></div>
                                <div class="w40 float-left">Michael Buble Hollywood</div>
                                <div class="w20 float-left"><div class="form-input float-left"> Horia Simon </div></div>
                                <div class="w10 float-left"><i class="glyph-icon icon-play-circle"></i></div>
                                <div class="w10 float-left"><center><i class="glyph-icon icon-remove-sign"></i></center></div>
                                <div class="w20 float-left"><div class="form-input float-left"> Horia Simon </div></div>
                                <div class="clearfix"></div>
                           
                                <div class="float-right cart-btnn">
                               </div>

                            </div>
                        </div>
                       </div>
                    </div>

                </form>
            </div>
        </div>


                <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
                <script src="../assets/js/jquery.metisMenu.js" type="text/javascript"></script>

<script>
    $(function () {

        $('#menu').metisMenu();

    });
</script>
    </body>
</html>

app/views/admin/users/new.html.erb
<h1>New admin_user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>