config/routes.rb
SociaLoginRails::Application.routes.draw do

  resources :genres

  root :to => 'pages#landing'
  namespace :admin do
    resources :users
    resources :admin_users
  end

  resources :roles

  resources :songs do
    match "get_30_seconds_song" , :via=>[:get]
  end
   
  #match "/admin_users" => "users#admin_users", :via=>[:get]
  match "/add_email" => "users#add_email" , :via=>"get"
  match "/users/save_email"=> "users#save_email", :via=>"post"
  get "pages/terms"
  get "pages/welcome"
  get "pages/landing"
  match "/twitter" => 'pages#landing' ,:via=>"get"
  devise_for :users, :controllers => {:passwords => "passwords",:omniauth_callbacks=> "omniauth_callbacks",:sessions => "api/v1/sessions",:registrations=>"api/v1/registrations"}
 resources :users
  


  namespace :api do
    namespace :v1 do
      #Sessions controller
      devise_scope :user do
        resources :sessions, :only => [:create, :destroy,:update,:api_current_user]
        match 'api_current_user/:id' => "sessions#api_current_user" ,:via => :get
        #        match 'all_users' => "sessions#all_users" ,:via => :get
        match 'date_today' => "sessions#date_today", :via => :get   
        match 'reset_password' => "sessions#reset_password", :via => :post
        match 'users' => "registrations#create" ,:via=>[:post]
        match 'edit' => "registrations#update" ,:via=>[:post]
      end
    end
  end
end

app/views/layouts/_flash_message.html.erb
<% if alert || flash[:alert] || flash[:error] %>
  <span class="alert alert-error">
    <a class="close" data-dismiss="alert" href="#">x</a>
    <center><h4 class="alert-heading">Error!</h4></center>
    <center><%= alert %></center>
    <center><%= flash[:error] %></center>
    <br/>
  </span>
<% end %>
<% if flash[:notice] %>
  <span class="alert-success">
    <a class="close" data-dismiss="alert" href="#">x</a>
    <center><h4 class="alert-heading">Success!</h4></center>
    <center><%= flash[:notice] %></center>
    <br/>
  </span>

<% end %>

<style>
  .alert-error{
    color: red;
  }
  .alert-success{
    color: green;
  }
</style>

app/views/layouts/_header.html.erb
<div class="navbar-header">
  <a href="../" class="navbar-brand" style="text-decoration:none;">Blue Music</a>
</div>
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li>
      Welcome <%= current_user.name %>!
    </li>
    <% if current_user && current_user.is_admin? %>
      <li>
        <%= link_to 'Manage User', admin_users_path, :class => 'navbar-link' %>
      </li>

      <li>
        <%= link_to 'Manage Admin', admin_admin_users_path, :class => 'navbar-link' %>
      </li>
      <li>
        <%= link_to 'Manage Genres', genres_path, :class => 'navbar-link' %>
      </li>
      <li>
        <%= link_to 'Manage Music', songs_path, :class => 'navbar-link' %>
      </li>
    <% end %>
    <li>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
    </li>
    <li>
      <%= link_to "Logout", destroy_user_session_path %>
    </li>
  <% else %>
    <li>
      <%= link_to "Sign in", new_user_session_path %>
    </li>
  <% end %>

</ul>
<div></div>
<div style="height:20px;"> <%= render "layouts/flash_message" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SociaLoginRails</title>
    <%#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-collapse collapse" id="navbar-main">
          <%= render "layouts/header" %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="page-header" id="banner">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>


<style>
  abbr, accronym{ border-bottom: 0px; }
</style>